### ISSUE TITLE
Doesn't work in iOS 8

### ISSUE THREAD

**Issue by zhouhao27** [appwilldev/AWIconSheet#1]
It will show a blank screen.

**Comment by ghost** [comment]
Sorry, since iOS 8 Apple change the uiactionsheet to uialertviewcontroller
. AWIconSheet cannot be layout .
We will rewrite this later  :D

2014-10-04 11:43 GMT+08:00 Zhou Hao notifications@github.com:

> It will show a blank screen.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/appwilldev/AWIconSheet/issues/1.

## 

---

_Great_ _minds_ _discuss_ _idea_.
Small _minds_ _discuss_ people.

## Average _minds_ _discuss_ events.

**Comment by geeklawyer** [comment]
Do you have an estimated date to update to iOS8? Thanks!

**Comment by Neeeo** [comment]
Please check the latest commit.
